# Generated by Django 3.1.1 on 2020-09-08 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=uuid.UUID('9865c337-2141-4141-8375-071b6705f2ec'), max_length=300),
        ),
    ]
